### ISSUE TITLE
Further developing

### ISSUE THREAD

**Issue by PoLaKoSz** [Brett-Tech-Networking/Moradi-AntiVirus#1]
Dear Developer Team!

I would like to contribute to this project but first I want to ask
- do You plan to maintain this project for a long time?
- is there a plan how the AV gonna recognize threats?

Thank You!
*Sorry for my English*

Have a nice day! :smile:

**Comment by matthew17754** [comment]
Hello fellow open-source developer,

We would love to have you be apart of our team. To answer your questions:
- Yes, we do plan to keep this project running for a long time. We will in the future implement into cross-platform systems as well to accommodate more users.
- In terms of recognizing threats, we're currently working on running a check to a server for known viruses on common virus databases. 

Much work remains on the scanner as well as the GUI, but we intend to continue development further, especially this upcoming summer. Feel free to submit pull-requests for whatever developments you would like to contribute. Welcome to the team.

matthew17754
Moradi-OS Project
BTN Representative

**Comment by PoLaKoSz** [comment]
Thank You for the fast response!
